-- DDL
-- ALTER : 객체를 수정하는 구문
-- 테이블 객체 수정 : ALTER TABLE 테이블명 수정할 내용;
-- 컬럼 추가/변경/삭제, 제약조건 추가/변경/삭제
-- 테이블명 변경, 제약조건 이름 변경

-- 컬럼 추가
SELECT
       DC.*
  FROM DEPT_COPY DC;
  
ALTER TABLE DEPT_COPY
ADD (LNAME VARCHAR2(20)); --ADD 컬럼 추가

SELECT * FROM DEPT_COPY;

-- 컬럼 삭제
ALTER TABLE DEPT_COPY
DROP COLUMN LNAME;

SELECT * FROM DEPT_COPY;

-- 컬럼 생성 시 DEFAULT 값 설정
ALTER TABLE DEPT_COPY
ADD (CNAME VARCHAR2(20) DEFAULT '한국'); --add 컬럼이름 자료형 제약조건;

SELECT * FROM DEPT_COPY;

-- 컬럼에 제약조건 추가
CREATE TABLE DEPT_COPY2
AS
SELECT *
  FROM DEPT_COPY;
  
SELECT * FROM DEPT_COPY2;

ALTER TABLE DEPT_COPY2
ADD CONSTRAINT PK_DEPT_ID2 PRIMARY KEY(DEPT_ID);

ALTER TABLE DEPT_COPY2
ADD CONSTRAINT UN_DEPT_TITLE UNIQUE(DEPT_TITLE);

--DEPT_COPY2에 LOCATION_ID를 NOT NULL로 추가해줄거야 
-- 제약조건 이름은 NN_LID
ALTER TABLE DEPT_COPY2
MODIFY LOCATION_ID CONSTRAINT NN_LID NOT NULL;

-- 컬럼 자료형 수정   -표현식 : 컬럼 이름 자로형 명시 ;;
ALTER TABLE DEPT_COPY2 
MODIFY DEPT_ID CHAR(3)
MODIFY DEPT_TITLE VARCHAR(30)
MODIFY LOCATION_ID VARCHAR(2);

-- DEFUALT 값 변경
ALTER TABLE DEPT_COPY
MODIFY CNAME DEFAULT '미국'; -- 기본값을 미국으로 수정

SELECT * FROM DEPT_COPY;

INSERT
  INTO DEPT_COPY
  VALUES ( 
   'D8' ,
   '생산부' ,
   'L2' ,
   DEFAULT --기본값 미국으로 추가
  );
  SELECT *FROM DEPT_COPY;
  
SELECT * FROM DEPT_COPY2; --복사한걸 바꿔도 기존에 한국으로 해놔서 바뀌지 않음

ALTER TABLE DEPT_COPY2
DROP COLUMN DEPT_TITLE; 

ALTER TABLE DEPT_COPY2 --copy2에 있는 location_id 삭제
DROP COLUMN LOCATION_ID;

-- 지우려는 테이블에 최소 한 개 이상의 컬럼이 남아 있어야 한다 (안그러면 테이블 자체가 사라진다)
ALTER TABLE DEPT_COPY2
DROP COLUMN DEPT_ID;

CREATE TABLE TB1(
 PK NUMBER PRIMARY KEY, 
 FK NUMBER REFERENCES TB1,
 COL1 NUMBER,
 CHECK(PK > 0 AND COL1 > 0) --제약조건, -1,0,null 안됌
);

ALTER TABLE TB1
DROP COLUMN PK; -- 안지워짐 이유는 pk,fk연관되어 있어서

ALTER TABLE TB1
DROP COLUMN PK CASCADE CONSTRAINT; -- 제약조건 삭제, PK 사라짐; 제약조건 명시 안해주면 다 사라짐 

SELECT *
  FROM TB1;
  
-- 컬럼 삭제
-- 테이블에는 최소 한 개 이상의 컬럼이 존재해야 한다 : 모든 컬럼 삭제는 불가능하다
-- 데이터가 기록되어 있는 컬럼도 삭제 가능함
-- 삭제된 컬럼은 복구가 안된다 
ALTER TABLE DEPT_COPY
DROP (CNAME, DEPT_TITLE, LOCATION_ID); --다중열 삭제

SELECT * FROM DEPT_COPY; --테이블의 값이 하나라도 남아 있어야 되서 남겨둠

ROLLBACK; -- 테이블이 하나밖에 없음
--오류!!!
CREATE TABLE CONST_EMP(              
  ENAME VARCHAR2(20) NOT NULL,
  ENO VARCHAR2(15) NOT NULL,
  MARRIAGE CHAR(1) DEFAULT 'N',
  EID CHAR(3),
  EMAIL VARCHAR2(30),
  JID CHAR(2),
  MID CHAR(3),
  DID CHAR(2),
  CONSTRAINT CK_MARRIAGE CHECK(MARRIAGE IN ('Y', 'N')),
  CONSTRAINT PK_EID PRIMARY KEY (EID),
  CONSTRAINT UN_END UNIQUE (ENO),
  CONSTRAINT UN_EMAIL UNIQUE(EMAIL),
  CONSTRAINT FK_JID FOREIGN KEY (JID) REFERENCES JOB(JOB_CODE) ON DELETE SET NULL,
  CONSTRAINT FK_MID FOREIGN KEY (MID) REFERENCES CONST_EMP ON DELETE SET NULL,
  CONSTRAINT FK_DID FOREIGN KEY (DID) REFERENCES DEPARTMENT ON DELETE CASCADE
);

ALTER TABLE CONST_EMP --제약조건 이름을 명시하면 삭제 가능
DROP CONSTRAINT CK_MARRIAGE;

ALTER TABLE CONST_EMP --다중 삭제 가능
DROP CONSTRAINT FK_DID --제약조건 이름 / constraint 제약조건을 명시 한 후에 삭제 가능
DROP CONSTRAINT FK_JID
DROP CONSTRAINT FK_MID;

ALTER TABLE CONST_EMP --제약조건을 변경
MODIFY (ENAME NULL, ENO NULL);

-- 컬럼 이름 변경
CREATE TABLE DEPT_COPY3
AS SELECT * FROM DEPARTMENT;

SELECT * FROM DEPT_COPY3;

ALTER TABLE DEPT_COPY3 RENAME COLUMN DEPT_ID TO DEPT_CODE; --현재 테이블에 있는 dept_id를 dept_code로 바꾸겠다

SELECT * FROM DEPT_COPY3;

ALTER TABLE DEPT_COPY3
ADD CONSTRAINT PK_DEPT_CODE3 PRIMARY KEY (DEPT_CODE); --제약조건 추가

ALTER TABLE DEPT_COPY3
RENAME CONSTRAINT PK_DEPT_CODE3 TO PK_DCODE; --제약조건의 이름을 pk_dcode로 바꿔줌

ALTER TABLE DEPT_COPY3 --테이블 이름 바꾸기
RENAME TO DEPT_TEST;

SELECT * FROM DEPT_TEST;

-- 테이블 삭제
DROP TABLE DEPT_TEST CASCADE CONSTRAINT; --관계 되어 있는 제약조건을 신경쓰지 않고 삭제하겠다
