CREATE USER C##chat1_1 IDENTIFIED BY bitc5600;
-- 계정에 권한주기
GRANT RESOURCE, CONNECT TO C##chat1_1;
--용량 제어 해제
ALTER USER C##chat1_1 QUOTA UNLIMITED ON SYSTEM;
ALTER USER C##chat1_1 QUOTA UNLIMITED ON USERS;

DROP USER C##chat1_1;


