DROP TABLE EMPLOYEE;

CREATE TABLE EMPLOYEE
(
    EMP_ID    VARCHAR2(3) NOT NULL,
    EMP_NAME    VARCHAR2(20) NOT NULL,
    SALARY    NUMBER NOT NULL,
    ANNUAL    NUMBER NOT NULL,
    JOB_CODE    VARCHAR2(2) NOT NULL,
    VEH_CODE    VARCHAR2(2) NOT NULL
);

COMMENT ON COLUMN EMPLOYEE.EMP_ID IS '사원번호';

COMMENT ON COLUMN EMPLOYEE.EMP_NAME IS '직원명';

COMMENT ON COLUMN EMPLOYEE.SALARY IS '월급';

COMMENT ON COLUMN EMPLOYEE.ANNUAL IS '연차';

COMMENT ON COLUMN EMPLOYEE.JOB_CODE IS '직급코드';

COMMENT ON COLUMN EMPLOYEE.VEH_CODE IS '출퇴근코드';

COMMENT ON TABLE EMPLOYEE IS '직원';

CREATE UNIQUE INDEX EMPLOYEE_PK ON EMPLOYEE
( EMP_ID );

ALTER TABLE EMPLOYEE
 ADD CONSTRAINT EMPLOYEE_PK PRIMARY KEY ( EMP_ID )
 USING INDEX EMPLOYEE_PK;




CREATE TABLE JOB
(
    JOB_CODE    VARCHAR2(2) NOT NULL,   
    JOB_NAME    VARCHAR2(35) NOT NULL
);

COMMENT ON COLUMN JOB.JOB_NAME IS '직급명';

COMMENT ON COLUMN JOB.JOB_CODE IS '직급코드';

COMMENT ON TABLE JOB IS '직급';

CREATE UNIQUE INDEX JOB_PK ON JOB
( JOB_CODE );

ALTER TABLE JOB
 ADD CONSTRAINT JOB_PK PRIMARY KEY ( JOB_CODE )
 USING INDEX JOB_PK;


DROP TABLE PRODUCT;

CREATE TABLE PRODUCT
(
    PRO_CODE    VARCHAR2(20) NOT NULL,
    PRO_NAME    VARCHAR2(20) NOT NULL,
    PRO_PRICE    NUMBER NOT NULL
);

COMMENT ON COLUMN PRODUCT.PRO_CODE IS '제품코드';

COMMENT ON COLUMN PRODUCT.PRO_NAME IS '제품명';

COMMENT ON COLUMN PRODUCT.PRO_PRICE IS '제품가격';

COMMENT ON TABLE PRODUCT IS '제품';

CREATE UNIQUE INDEX PRODUCT_PK ON PRODUCT
( PRO_CODE );

ALTER TABLE PRODUCT
 ADD CONSTRAINT PRODUCT_PK PRIMARY KEY ( PRO_CODE )
 USING INDEX PRODUCT_PK;


DROP TABLE SALES;

CREATE TABLE SALES
(
    EMP_ID    VARCHAR2(3) NOT NULL,
    PRO_CODE    VARCHAR2(20) NOT NULL,
    PRO_AMOUNT    NUMBER NOT NULL,
    PRO_NAME    NUMBER NOT NULL,
    PRO_DATE    DATE NOT NULL,
    PRO_PAY    NUMBER NOT NULL
);

COMMENT ON COLUMN SALES.EMP_ID IS '사원번호';

COMMENT ON COLUMN SALES.PRO_CODE IS '제품코드';

COMMENT ON COLUMN SALES.PRO_AMOUNT IS '판매수';

COMMENT ON COLUMN SALES.PRO_NAME IS '판매번호';

COMMENT ON COLUMN SALES.PRO_DATE IS '판매일';

COMMENT ON COLUMN SALES.PRO_PAY IS '결제금액';

COMMENT ON TABLE SALES IS '판매';

CREATE UNIQUE INDEX SALES_PK ON SALES
( PRO_NAME );

ALTER TABLE SALES
 ADD CONSTRAINT SALES_PK PRIMARY KEY ( PRO_NAME )
 USING INDEX SALES_PK;


DROP TABLE VEHICLE;

CREATE TABLE VEHICLE
(
    VEH_CODE    VARCHAR2(2) NOT NULL,
    VEH_NAME    VARCHAR2(20) NOT NULL
);

COMMENT ON COLUMN VEHICLE.VEH_CODE IS '출퇴근코드';

COMMENT ON COLUMN VEHICLE.VEH_NAME IS '수단명';

COMMENT ON TABLE VEHICLE IS '출퇴근수단';

CREATE UNIQUE INDEX VEHICLE_PK ON VEHICLE
( VEH_CODE );

ALTER TABLE VEHICLE
 ADD CONSTRAINT VEHICLE_PK PRIMARY KEY ( VEH_CODE )
 USING INDEX VEHICLE_PK;



