DROP TABLE ANSWER;

CREATE TABLE ANSWER
(
    A_NUMBER    NUMBER NOT NULL,
    A_NUMBER1    NUMBER NOT NULL,
    A_DEPTH    VARCHAR2(30) NOT NULL,
    A_DATE    VARCHAR2(30) NOT NULL,
    A_CONTENT    VARCHAR2(500) NOT NULL,
    M_NUMBER    NUMBER NOT NULL,
    C_NUMBER    NUMBER NOT NULL
);

COMMENT ON COLUMN ANSWER.A_NUMBER IS '댓글번호';

COMMENT ON COLUMN ANSWER.A_NUMBER1 IS '대댓글 번호';

COMMENT ON COLUMN ANSWER.A_DEPTH IS '뎁스';

COMMENT ON COLUMN ANSWER.A_DATE IS '작성일';

COMMENT ON COLUMN ANSWER.A_CONTENT IS '내용';

COMMENT ON COLUMN ANSWER.M_NUMBER IS '회원번호';

COMMENT ON COLUMN ANSWER.C_NUMBER IS '상담신청번호';

COMMENT ON TABLE ANSWER IS '댓글테이블';

CREATE UNIQUE INDEX ANSWER_PK ON ANSWER
( A_NUMBER );

ALTER TABLE ANSWER
 ADD CONSTRAINT ANSWER_PK PRIMARY KEY ( A_NUMBER )
 USING INDEX ANSWER_PK;


DROP TABLE CONSULTING;

CREATE TABLE CONSULTING
(
    C_DONG    VARCHAR2(30) NOT NULL,
    C_DETAIL    VARCHAR2(500) NOT NULL,
    C_NUMBER    NUMBER NOT NULL,
    C_SITUATION    VARCHAR2(30) NOT NULL,
    M_NUMBER    NUMBER NOT NULL
);

COMMENT ON COLUMN CONSULTING.C_DONG IS '동코드';

COMMENT ON COLUMN CONSULTING.C_DETAIL IS '문의내용';

COMMENT ON COLUMN CONSULTING.C_NUMBER IS '상담신청번호';

COMMENT ON COLUMN CONSULTING.C_SITUATION IS '상태';

COMMENT ON COLUMN CONSULTING.M_NUMBER IS '회원번호';

COMMENT ON TABLE CONSULTING IS '창업상담';

CREATE UNIQUE INDEX CONSULTING_PK ON CONSULTING
( C_NUMBER );

ALTER TABLE CONSULTING
 ADD CONSTRAINT CONSULTING_PK PRIMARY KEY ( C_NUMBER )
 USING INDEX CONSULTING_PK;


DROP TABLE MEMBER;

CREATE TABLE MEMBER
(
    M_ID    VARCHAR2(30) NOT NULL,
    M_PW    VARCHAR2(30) NOT NULL,
    M_NAME    VARCHAR2(30) NOT NULL,
    M_BIRTH    NUMBER NOT NULL,
    M_PHONE    NUMBER NOT NULL,
    M_NUMBER    NUMBER NOT NULL,
    M_SITUATION    VARCHAR2(30) NOT NULL,
    M_RATING    NUMBER NOT NULL
);

COMMENT ON COLUMN MEMBER.M_ID IS '아이디';

COMMENT ON COLUMN MEMBER.M_PW IS '비밀번호';

COMMENT ON COLUMN MEMBER.M_NAME IS '이름';

COMMENT ON COLUMN MEMBER.M_BIRTH IS '생년월일';

COMMENT ON COLUMN MEMBER.M_PHONE IS '전화번호';

COMMENT ON COLUMN MEMBER.M_NUMBER IS '회원번호';

COMMENT ON COLUMN MEMBER.M_SITUATION IS '상태';

COMMENT ON COLUMN MEMBER.M_RATING IS '등급';

COMMENT ON TABLE MEMBER IS '회원';

CREATE UNIQUE INDEX MEMBER_PK ON MEMBER
( M_NUMBER );

ALTER TABLE MEMBER
 ADD CONSTRAINT MEMBER_PK PRIMARY KEY ( M_NUMBER )
 USING INDEX MEMBER_PK;


