DROP TABLE BLOG;

CREATE TABLE BLOG
(
    B_NUMBER    VARCHAR2(30) NOT NULL,
    M_NUMBER    VARCHAR2(10) NOT NULL,
    B_NAME    VARCHAR2(30) NOT NULL,
    B_BACK    VARCHAR2(100),
    B_INTRO    VARCHAR2(100),
    B_SITUATION    VARCHAR2(30) NOT NULL
);

COMMENT ON COLUMN BLOG.B_NUMBER IS '블로그번호';

COMMENT ON COLUMN BLOG.M_NUMBER IS '회원번호';

COMMENT ON COLUMN BLOG.B_NAME IS '블로그이름';

COMMENT ON COLUMN BLOG.B_BACK IS '블로그배경';

COMMENT ON COLUMN BLOG.B_INTRO IS '블로그소개';

COMMENT ON COLUMN BLOG.B_SITUATION IS '상태';

COMMENT ON TABLE BLOG IS '블로그';

CREATE UNIQUE INDEX BLOG_PK ON BLOG
( B_NUMBER );

ALTER TABLE BLOG
 ADD CONSTRAINT BLOG_PK PRIMARY KEY ( B_NUMBER )
 USING INDEX BLOG_PK;


DROP TABLE CATEGORY;

CREATE TABLE CATEGORY
(
    C_NUMBER    NUMBER NOT NULL,
    C_NAME    VARCHAR2(30) NOT NULL,
    C_CLASSIFY    VARCHAR2(30),
    C_SITUATION    VARCHAR2(30) NOT NULL,
    B_NUMBER    VARCHAR2(30)
);

COMMENT ON COLUMN CATEGORY.C_NUMBER IS '카테고리 번호';

COMMENT ON COLUMN CATEGORY.C_NAME IS '카테고리 명';

COMMENT ON COLUMN CATEGORY.C_CLASSIFY IS '카테고리 분류';

COMMENT ON COLUMN CATEGORY.C_SITUATION IS '상태';

COMMENT ON COLUMN CATEGORY.B_NUMBER IS '블로그번호';

COMMENT ON TABLE CATEGORY IS '카테고리';

CREATE UNIQUE INDEX CATEGORY_PK ON CATEGORY
( C_NUMBER );

ALTER TABLE CATEGORY
 ADD CONSTRAINT CATEGORY_PK PRIMARY KEY ( C_NUMBER )
 USING INDEX CATEGORY_PK;


DROP TABLE MEMBER;

CREATE TABLE MEMBER
(
    M_NUMBER    VARCHAR2(10) NOT NULL,
    M_ID    VARCHAR2(30) NOT NULL,
    M_PW    VARCHAR2(30) NOT NULL,
    M_NICKNAME    VARCHAR2(30) NOT NULL,
    M_NAME    VARCHAR2(30) NOT NULL
);

COMMENT ON COLUMN MEMBER.M_NUMBER IS '회원번호';

COMMENT ON COLUMN MEMBER.M_ID IS '회원아이디';

COMMENT ON COLUMN MEMBER.M_PW IS '비밀번호';

COMMENT ON COLUMN MEMBER.M_NICKNAME IS '닉네임';

COMMENT ON COLUMN MEMBER.M_NAME IS '이름';

COMMENT ON TABLE MEMBER IS '회원';

CREATE UNIQUE INDEX MEMBER_PK ON MEMBER
( M_NUMBER );

ALTER TABLE MEMBER
 ADD CONSTRAINT MEMBER_PK PRIMARY KEY ( M_NUMBER )
 USING INDEX MEMBER_PK;


DROP TABLE POST;

CREATE TABLE POST
(
    P_NUMBER    NUMBER NOT NULL,
    B_NUMBER    NUMBER NOT NULL,
    P_TITLE    VARCHAR2(30) NOT NULL,
    P_DETAIL    VARCHAR2(1000) NOT NULL,
    P_TIME    DATE NOT NULL,
    P_SITUATION    VARCHAR2(30) NOT NULL,
    C_NUMBER    NUMBER
);

COMMENT ON COLUMN POST.P_NUMBER IS '포스팅번호';

COMMENT ON COLUMN POST.B_NUMBER IS '블로그번호';

COMMENT ON COLUMN POST.P_TITLE IS '제목';

COMMENT ON COLUMN POST.P_DETAIL IS '내용';

COMMENT ON COLUMN POST.P_TIME IS '작성시간';

COMMENT ON COLUMN POST.P_SITUATION IS '상태';

COMMENT ON COLUMN POST.C_NUMBER IS '카테고리 번호';

COMMENT ON TABLE POST IS '포스팅';

CREATE UNIQUE INDEX POST_PK ON POST
( P_NUMBER );

ALTER TABLE POST
 ADD CONSTRAINT POST_PK PRIMARY KEY ( P_NUMBER )
 USING INDEX POST_PK;


DROP TABLE SYMPATHY;

CREATE TABLE SYMPATHY
(
    B_NUMBER    VARCHAR2(30) NOT NULL,
    P_NUMBER    NUMBER
);

COMMENT ON COLUMN SYMPATHY.B_NUMBER IS '블로그번호';

COMMENT ON COLUMN SYMPATHY.P_NUMBER IS '포스팅번호';

COMMENT ON TABLE SYMPATHY IS '공감';


